//
//  NGAFontNames.swift
//  NGAClasses
//
//  Created by Jose Castellanos on 6/11/15.
//  Copyright (c) 2015 NextGen Apps LLC. All rights reserved.
//

import Foundation

public enum FontName:String {
    case AcademyEngravedLetPlain
    case AlNile
    case AlNileBold = "AlNile-Bold"
    case AmericanTypewriter
    case AmericanTypewriterBold = "AmericanTypewriter-Bold"
    case AmericanTypewriterCondensed = "AmericanTypewriter-Condensed"
    case AmericanTypewriterCondensedBold = "AmericanTypewriter-CondensedBold"
    case AmericanTypewriterCondensedLight = "AmericanTypewriter-CondensedLight"
    case AmericanTypewriterLight = "AmericanTypewriter-Light"
    case AppleColorEmoji
    case AppleSDGothicNeoBold = "AppleSDGothicNeo-Bold"
    case AppleSDGothicNeoLight = "AppleSDGothicNeo-Light"
    case AppleSDGothicNeoMedium = "AppleSDGothicNeo-Medium"
    case AppleSDGothicNeoRegular = "AppleSDGothicNeo-Regular"
    case AppleSDGothicNeoSemiBold = "AppleSDGothicNeo-SemiBold"
    case AppleSDGothicNeoThin = "AppleSDGothicNeo-Thin"
    case AppleSDGothicNeoUltraLight = "AppleSDGothicNeo-UltraLight"
    case ArialBoldItalicMT = "Arial-BoldItalicMT"
    case ArialBoldMT = "Arial-BoldMT"
    case ArialItalicMT = "Arial-ItalicMT"
    case ArialMT
    case ArialHebrew
    case ArialHebrewBold = "ArialHebrew-Bold"
    case ArialHebrewLight = "ArialHebrew-Light"
    case ArialRoundedMTBold
    case AvenirBlack = "Avenir-Black"
    case AvenirBlackOblique = "Avenir-BlackOblique"
    case AvenirBook = "Avenir-Book"
    case AvenirBookOblique = "Avenir-BookOblique"
    case AvenirHeavy = "Avenir-Heavy"
    case AvenirHeavyOblique = "Avenir-HeavyOblique"
    case AvenirLight = "Avenir-Light"
    case AvenirLightOblique = "Avenir-LightOblique"
    case AvenirMedium = "Avenir-Medium"
    case AvenirMediumOblique = "Avenir-MediumOblique"
    case AvenirOblique = "Avenir-Oblique"
    case AvenirRoman = "Avenir-Roman"
    case AvenirNextBold = "AvenirNext-Bold"
    case AvenirNextBoldItalic = "AvenirNext-BoldItalic"
    case AvenirNextDemiBold = "AvenirNext-DemiBold"
    case AvenirNextDemiBoldItalic = "AvenirNext-DemiBoldItalic"
    case AvenirNextHeavy = "AvenirNext-Heavy"
    case AvenirNextHeavyItalic = "AvenirNext-HeavyItalic"
    case AvenirNextItalic = "AvenirNext-Italic"
    case AvenirNextMedium = "AvenirNext-Medium"
    case AvenirNextMediumItalic = "AvenirNext-MediumItalic"
    case AvenirNextRegular = "AvenirNext-Regular"
    case AvenirNextUltraLight = "AvenirNext-UltraLight"
    case AvenirNextUltraLightItalic = "AvenirNext-UltraLightItalic"
    case AvenirNextCondensedBold = "AvenirNextCondensed-Bold"
    case AvenirNextCondensedBoldItalic = "AvenirNextCondensed-BoldItalic"
    case AvenirNextCondensedDemiBold = "AvenirNextCondensed-DemiBold"
    case AvenirNextCondensedDemiBoldItalic = "AvenirNextCondensed-DemiBoldItalic"
    case AvenirNextCondensedHeavy = "AvenirNextCondensed-Heavy"
    case AvenirNextCondensedHeavyItalic = "AvenirNextCondensed-HeavyItalic"
    case AvenirNextCondensedItalic = "AvenirNextCondensed-Italic"
    case AvenirNextCondensedMedium = "AvenirNextCondensed-Medium"
    case AvenirNextCondensedMediumItalic = "AvenirNextCondensed-MediumItalic"
    case AvenirNextCondensedRegular = "AvenirNextCondensed-Regular"
    case AvenirNextCondensedUltraLight = "AvenirNextCondensed-UltraLight"
    case AvenirNextCondensedUltraLightItalic = "AvenirNextCondensed-UltraLightItalic"
    case Baskerville
    case BaskervilleBold = "Baskerville-Bold"
    case BaskervilleBoldItalic = "Baskerville-BoldItalic"
    case BaskervilleItalic = "Baskerville-Italic"
    case BaskervilleSemiBold = "Baskerville-SemiBold"
    case BaskervilleSemiBoldItalic = "Baskerville-SemiBoldItalic"
    case BodoniSvtyTwoITCTTBold = "BodoniSvtyTwoITCTT-Bold"
    case BodoniSvtyTwoITCTTBook = "BodoniSvtyTwoITCTT-Book"
    case BodoniSvtyTwoITCTTBookIta = "BodoniSvtyTwoITCTT-BookIta"
    case BodoniSvtyTwoOSITCTTBold = "BodoniSvtyTwoOSITCTT-Bold"
    case BodoniSvtyTwoOSITCTTBook = "BodoniSvtyTwoOSITCTT-Book"
    case BodoniSvtyTwoOSITCTTBookIt = "BodoniSvtyTwoOSITCTT-BookIt"
    case BodoniSvtyTwoSCITCTTBook = "BodoniSvtyTwoSCITCTT-Book"
    case BodoniOrnamentsITCTT
    case BradleyHandITCTTBold = "BradleyHandITCTT-Bold"
    case ChalkboardSEBold = "ChalkboardSE-Bold"
    case ChalkboardSELight = "ChalkboardSE-Light"
    case ChalkboardSERegular = "ChalkboardSE-Regular"
    case Chalkduster
    case Cochin
    case CochinBold = "Cochin-Bold"
    case CochinBoldItalic = "Cochin-BoldItalic"
    case CochinItalic = "Cochin-Italic"
    case Copperplate
    case CopperplateBold = "Copperplate-Bold"
    case CopperplateLight = "Copperplate-Light"
    case Courier
    case CourierBold = "Courier-Bold"
    case CourierBoldOblique = "Courier-BoldOblique"
    case CourierOblique = "Courier-Oblique"
    case CourierNewPSBoldItalicMT = "CourierNewPS-BoldItalicMT"
    case CourierNewPSBoldMT = "CourierNewPS-BoldMT"
    case CourierNewPSItalicMT = "CourierNewPS-ItalicMT"
    case CourierNewPSMT
    case Damascus
    case DamascusBold
    case DamascusLight
    case DamascusMedium
    case DamascusSemiBold
    case DevanagariSangamMN
    case DevanagariSangamMNBold = "DevanagariSangamMN-Bold"
    case Didot
    case DidotBold = "Didot-Bold"
    case DidotItalic = "Didot-Italic"
    case EuphemiaUCAS
    case EuphemiaUCASBold = "EuphemiaUCAS-Bold"
    case EuphemiaUCASItalic = "EuphemiaUCAS-Italic"
    case Farah
    case FuturaCondensedExtraBold = "Futura-CondensedExtraBold"
    case FuturaCondensedMedium = "Futura-CondensedMedium"
    case FuturaMedium = "Futura-Medium"
    case FuturaMediumItalic = "Futura-MediumItalic"
    case GeezaPro
    case GeezaProBold = "GeezaPro-Bold"
    case Georgia
    case GeorgiaBold = "Georgia-Bold"
    case GeorgiaBoldItalic = "Georgia-BoldItalic"
    case GeorgiaItalic = "Georgia-Italic"
    case GillSans
    case GillSansBold = "GillSans-Bold"
    case GillSansBoldItalic = "GillSans-BoldItalic"
    case GillSansItalic = "GillSans-Italic"
    case GillSansLight = "GillSans-Light"
    case GillSansLightItalic = "GillSans-LightItalic"
    case GillSansSemiBold = "GillSans-SemiBold"
    case GillSansSemiBoldItalic = "GillSans-SemiBoldItalic"
    case GillSansUltraBold = "GillSans-UltraBold"
    case GujaratiSangamMN
    case GujaratiSangamMNBold = "GujaratiSangamMN-Bold"
    case GurmukhiMN
    case GurmukhiMNBold = "GurmukhiMN-Bold"
    case Helvetica
    case HelveticaBold = "Helvetica-Bold"
    case HelveticaBoldOblique = "Helvetica-BoldOblique"
    case HelveticaLight = "Helvetica-Light"
    case HelveticaLightOblique = "Helvetica-LightOblique"
    case HelveticaOblique = "Helvetica-Oblique"
    case HelveticaNeue
    case HelveticaNeueBold = "HelveticaNeue-Bold"
    case HelveticaNeueBoldItalic = "HelveticaNeue-BoldItalic"
    case HelveticaNeueCondensedBlack = "HelveticaNeue-CondensedBlack"
    case HelveticaNeueCondensedBold = "HelveticaNeue-CondensedBold"
    case HelveticaNeueItalic = "HelveticaNeue-Italic"
    case HelveticaNeueLight = "HelveticaNeue-Light"
    case HelveticaNeueLightItalic = "HelveticaNeue-LightItalic"
    case HelveticaNeueMedium = "HelveticaNeue-Medium"
    case HelveticaNeueMediumItalic = "HelveticaNeue-MediumItalic"
    case HelveticaNeueThin = "HelveticaNeue-Thin"
    case HelveticaNeueThinItalic = "HelveticaNeue-ThinItalic"
    case HelveticaNeueUltraLight = "HelveticaNeue-UltraLight"
    case HelveticaNeueUltraLightItalic = "HelveticaNeue-UltraLightItalic"
    case HiraMinProNW3 = "HiraMinProN-W3"
    case HiraMinProNW6 = "HiraMinProN-W6"
    case HiraginoSansW3 = "HiraginoSans-W3"
    case HiraginoSansW6 = "HiraginoSans-W6"
    case HoeflerTextBlack = "HoeflerText-Black"
    case HoeflerTextBlackItalic = "HoeflerText-BlackItalic"
    case HoeflerTextItalic = "HoeflerText-Italic"
    case HoeflerTextRegular = "HoeflerText-Regular"
    case IowanOldStyleBold = "IowanOldStyle-Bold"
    case IowanOldStyleBoldItalic = "IowanOldStyle-BoldItalic"
    case IowanOldStyleItalic = "IowanOldStyle-Italic"
    case IowanOldStyleRoman = "IowanOldStyle-Roman"
    case Kailasa
    case KailasaBold = "Kailasa-Bold"
    case KannadaSangamMN
    case KannadaSangamMNBold = "KannadaSangamMN-Bold"
    case KhmerSangamMN
    case KohinoorBanglaLight = "KohinoorBangla-Light"
    case KohinoorBanglaRegular = "KohinoorBangla-Regular"
    case KohinoorBanglaSemibold = "KohinoorBangla-Semibold"
    case KohinoorDevanagariLight = "KohinoorDevanagari-Light"
    case KohinoorDevanagariRegular = "KohinoorDevanagari-Regular"
    case KohinoorDevanagariSemibold = "KohinoorDevanagari-Semibold"
    case KohinoorTeluguLight = "KohinoorTelugu-Light"
    case KohinoorTeluguMedium = "KohinoorTelugu-Medium"
    case KohinoorTeluguRegular = "KohinoorTelugu-Regular"
    case LaoSangamMN
    case MalayalamSangamMN
    case MalayalamSangamMNBold = "MalayalamSangamMN-Bold"
    case MarkerFeltThin = "MarkerFelt-Thin"
    case MarkerFeltWide = "MarkerFelt-Wide"
    case MenloBold = "Menlo-Bold"
    case MenloBoldItalic = "Menlo-BoldItalic"
    case MenloItalic = "Menlo-Italic"
    case MenloRegular = "Menlo-Regular"
    case DiwanMishafi
    case NoteworthyBold = "Noteworthy-Bold"
    case NoteworthyLight = "Noteworthy-Light"
    case OptimaBold = "Optima-Bold"
    case OptimaBoldItalic = "Optima-BoldItalic"
    case OptimaExtraBlack = "Optima-ExtraBlack"
    case OptimaItalic = "Optima-Italic"
    case OptimaRegular = "Optima-Regular"
    case OriyaSangamMN
    case OriyaSangamMNBold = "OriyaSangamMN-Bold"
    case PalatinoBold = "Palatino-Bold"
    case PalatinoBoldItalic = "Palatino-BoldItalic"
    case PalatinoItalic = "Palatino-Italic"
    case PalatinoRoman = "Palatino-Roman"
    case Papyrus
    case PapyrusCondensed = "Papyrus-Condensed"
    case PartyLetPlain
    case PingFangHKLight = "PingFangHK-Light"
    case PingFangHKMedium = "PingFangHK-Medium"
    case PingFangHKRegular = "PingFangHK-Regular"
    case PingFangHKSemibold = "PingFangHK-Semibold"
    case PingFangHKThin = "PingFangHK-Thin"
    case PingFangHKUltralight = "PingFangHK-Ultralight"
    case PingFangSCLight = "PingFangSC-Light"
    case PingFangSCMedium = "PingFangSC-Medium"
    case PingFangSCRegular = "PingFangSC-Regular"
    case PingFangSCSemibold = "PingFangSC-Semibold"
    case PingFangSCThin = "PingFangSC-Thin"
    case PingFangSCUltralight = "PingFangSC-Ultralight"
    case PingFangTCLight = "PingFangTC-Light"
    case PingFangTCMedium = "PingFangTC-Medium"
    case PingFangTCRegular = "PingFangTC-Regular"
    case PingFangTCSemibold = "PingFangTC-Semibold"
    case PingFangTCThin = "PingFangTC-Thin"
    case PingFangTCUltralight = "PingFangTC-Ultralight"
    case SavoyeLetPlain
    case SinhalaSangamMN
    case SinhalaSangamMNBold = "SinhalaSangamMN-Bold"
    case SnellRoundhand
    case SnellRoundhandBlack = "SnellRoundhand-Black"
    case SnellRoundhandBold = "SnellRoundhand-Bold"
    case Symbol
    case TamilSangamMN
    case TamilSangamMNBold = "TamilSangamMN-Bold"
    case Thonburi
    case ThonburiBold = "Thonburi-Bold"
    case ThonburiLight = "Thonburi-Light"
    case TimesNewRomanPSBoldItalicMT = "TimesNewRomanPS-BoldItalicMT"
    case TimesNewRomanPSBoldMT = "TimesNewRomanPS-BoldMT"
    case TimesNewRomanPSItalicMT = "TimesNewRomanPS-ItalicMT"
    case TimesNewRomanPSMT
    case TrebuchetBoldItalic = "Trebuchet-BoldItalic"
    case TrebuchetMS
    case TrebuchetMSBold = "TrebuchetMS-Bold"
    case TrebuchetMSItalic = "TrebuchetMS-Italic"
    case Verdana
    case VerdanaBold = "Verdana-Bold"
    case VerdanaBoldItalic = "Verdana-BoldItalic"
    case VerdanaItalic = "Verdana-Italic"
    case ZapfDingbatsITC
    case Zapfino
    
    public func fontWithSize(_ size:CGFloat) -> UIFont? {
        return UIFont(name: self, size: size)
    }
}

public extension UIFont {
    convenience init?(name:FontName, size: CGFloat) {
        self.init(name: name.rawValue, size: size)
    }
    class func printFontNameEnum() {
        print("public enum FontName:String {")
        let familyNames = UIFont.familyNames.sorted()
        for family in familyNames {
            let fontNames = UIFont.fontNames(forFamilyName: family).sorted()
            for font in fontNames {
                if font.containsString("-", caseInsensitive: false) {
                    let f = font.replacingOccurrences(of: "-", with: "")
                    print("case \(f) = \"\(font)\"")
                } else {
                    print("case \(font)")
                }
            }
        }
        print("}")
    }
}


//// Deprecating
public struct NGAFontNames {
    
    public static let MarionItalic = "Marion-Italic"
    public static let MarionBold = "Marion-Bold"
    public static let MarionRegular = "Marion-Regular"
    public static let CopperplateLight = "Copperplate-Light"
    public static let Copperplate = "Copperplate"
    public static let CopperplateBold = "Copperplate-Bold"
    public static let STHeitiSCMedium = "STHeitiSC-Medium"
    public static let STHeitiSCLight = "STHeitiSC-Light"
    public static let IowanOldStyleItalic = "IowanOldStyle-Italic"
    public static let IowanOldStyleRoman = "IowanOldStyle-Roman"
    public static let IowanOldStyleBoldItalic = "IowanOldStyle-BoldItalic"
    public static let IowanOldStyleBold = "IowanOldStyle-Bold"
    public static let CourierNewPSBoldMT = "CourierNewPS-BoldMT"
    public static let CourierNewPSItalicMT = "CourierNewPS-ItalicMT"
    public static let CourierNewPSMT = "CourierNewPSMT"
    public static let CourierNewPSBoldItalicMT = "CourierNewPS-BoldItalicMT"
    public static let AppleSDGothicNeoBold = "AppleSDGothicNeo-Bold"
    public static let AppleSDGothicNeoThin = "AppleSDGothicNeo-Thin"
    public static let AppleSDGothicNeoUltraLight = "AppleSDGothicNeo-UltraLight"
    public static let AppleSDGothicNeoRegular = "AppleSDGothicNeo-Regular"
    public static let AppleSDGothicNeoLight = "AppleSDGothicNeo-Light"
    public static let AppleSDGothicNeoMedium = "AppleSDGothicNeo-Medium"
    public static let AppleSDGothicNeoSemiBold = "AppleSDGothicNeo-SemiBold"
    public static let STHeitiTCMedium = "STHeitiTC-Medium"
    public static let STHeitiTCLight = "STHeitiTC-Light"
    public static let GillSansItalic = "GillSans-Italic"
    public static let GillSansBold = "GillSans-Bold"
    public static let GillSansBoldItalic = "GillSans-BoldItalic"
    public static let GillSansLightItalic = "GillSans-LightItalic"
    public static let GillSans = "GillSans"
    public static let GillSansLight = "GillSans-Light"
    public static let GillSansSemiBold = "GillSans-SemiBold"
    public static let GillSansSemiBoldItalic = "GillSans-SemiBoldItalic"
    public static let GillSansUltraBold = "GillSans-UltraBold"
    public static let MarkerFeltThin = "MarkerFelt-Thin"
    public static let MarkerFeltWide = "MarkerFelt-Wide"
    public static let Thonburi = "Thonburi"
    public static let ThonburiBold = "Thonburi-Bold"
    public static let ThonburiLight = "Thonburi-Light"
    public static let AvenirNextCondensedBoldItalic = "AvenirNextCondensed-BoldItalic"
    public static let AvenirNextCondensedHeavy = "AvenirNextCondensed-Heavy"
    public static let AvenirNextCondensedMedium = "AvenirNextCondensed-Medium"
    public static let AvenirNextCondensedRegular = "AvenirNextCondensed-Regular"
    public static let AvenirNextCondensedHeavyItalic = "AvenirNextCondensed-HeavyItalic"
    public static let AvenirNextCondensedMediumItalic = "AvenirNextCondensed-MediumItalic"
    public static let AvenirNextCondensedItalic = "AvenirNextCondensed-Italic"
    public static let AvenirNextCondensedUltraLightItalic = "AvenirNextCondensed-UltraLightItalic"
    public static let AvenirNextCondensedDemiBold = "AvenirNextCondensed-DemiBold"
    public static let AvenirNextCondensedUltraLight = "AvenirNextCondensed-UltraLight"
    public static let AvenirNextCondensedBold = "AvenirNextCondensed-Bold"
    public static let AvenirNextCondensedDemiBoldItalic = "AvenirNextCondensed-DemiBoldItalic"
    public static let TamilSangamMN = "TamilSangamMN"
    public static let TamilSangamMNBold = "TamilSangamMN-Bold"
    public static let HelveticaNeueItalic = "HelveticaNeue-Italic"
    public static let HelveticaNeueBold = "HelveticaNeue-Bold"
    public static let HelveticaNeueUltraLight = "HelveticaNeue-UltraLight"
    public static let HelveticaNeueCondensedBlack = "HelveticaNeue-CondensedBlack"
    public static let HelveticaNeueBoldItalic = "HelveticaNeue-BoldItalic"
    public static let HelveticaNeueCondensedBold = "HelveticaNeue-CondensedBold"
    public static let HelveticaNeueMedium = "HelveticaNeue-Medium"
    public static let HelveticaNeueLight = "HelveticaNeue-Light"
    public static let HelveticaNeueThin = "HelveticaNeue-Thin"
    public static let HelveticaNeueThinItalic = "HelveticaNeue-ThinItalic"
    public static let HelveticaNeueLightItalic = "HelveticaNeue-LightItalic"
    public static let HelveticaNeueUltraLightItalic = "HelveticaNeue-UltraLightItalic"
    public static let HelveticaNeueMediumItalic = "HelveticaNeue-MediumItalic"
    public static let HelveticaNeue = "HelveticaNeue"
    public static let GurmukhiMNBold = "GurmukhiMN-Bold"
    public static let GurmukhiMN = "GurmukhiMN"
    public static let TimesNewRomanPSMT = "TimesNewRomanPSMT"
    public static let TimesNewRomanPSBoldItalicMT = "TimesNewRomanPS-BoldItalicMT"
    public static let TimesNewRomanPSItalicMT = "TimesNewRomanPS-ItalicMT"
    public static let TimesNewRomanPSBoldMT = "TimesNewRomanPS-BoldMT"
    public static let GeorgiaBoldItalic = "Georgia-BoldItalic"
    public static let Georgia = "Georgia"
    public static let GeorgiaItalic = "Georgia-Italic"
    public static let GeorgiaBold = "Georgia-Bold"
    public static let AppleColorEmoji = "AppleColorEmoji"
    public static let ArialRoundedMTBold = "ArialRoundedMTBold"
    public static let KailasaBold = "Kailasa-Bold"
    public static let Kailasa = "Kailasa"
    public static let KohinoorDevanagariLight = "KohinoorDevanagari-Light"
    public static let KohinoorDevanagariMedium = "KohinoorDevanagari-Medium"
    public static let KohinoorDevanagariBook = "KohinoorDevanagari-Book"
    public static let SinhalaSangamMNBold = "SinhalaSangamMN-Bold"
    public static let SinhalaSangamMN = "SinhalaSangamMN"
    public static let ChalkboardSEBold = "ChalkboardSE-Bold"
    public static let ChalkboardSELight = "ChalkboardSE-Light"
    public static let ChalkboardSERegular = "ChalkboardSE-Regular"
    public static let SuperclarendonItalic = "Superclarendon-Italic"
    public static let SuperclarendonBlack = "Superclarendon-Black"
    public static let SuperclarendonLightItalic = "Superclarendon-LightItalic"
    public static let SuperclarendonBlackItalic = "Superclarendon-BlackItalic"
    public static let SuperclarendonBoldItalic = "Superclarendon-BoldItalic"
    public static let SuperclarendonLight = "Superclarendon-Light"
    public static let SuperclarendonRegular = "Superclarendon-Regular"
    public static let SuperclarendonBold = "Superclarendon-Bold"
    public static let GujaratiSangamMNBold = "GujaratiSangamMN-Bold"
    public static let GujaratiSangamMN = "GujaratiSangamMN"
    public static let DamascusLight = "DamascusLight"
    public static let DamascusBold = "DamascusBold"
    public static let DamascusSemiBold = "DamascusSemiBold"
    public static let DamascusMedium = "DamascusMedium"
    public static let Damascus = "Damascus"
    public static let NoteworthyLight = "Noteworthy-Light"
    public static let NoteworthyBold = "Noteworthy-Bold"
    public static let GeezaPro = "GeezaPro"
    public static let GeezaProBold = "GeezaPro-Bold"
    public static let AvenirMedium = "Avenir-Medium"
    public static let AvenirHeavyOblique = "Avenir-HeavyOblique"
    public static let AvenirBook = "Avenir-Book"
    public static let AvenirLight = "Avenir-Light"
    public static let AvenirRoman = "Avenir-Roman"
    public static let AvenirBookOblique = "Avenir-BookOblique"
    public static let AvenirBlack = "Avenir-Black"
    public static let AvenirMediumOblique = "Avenir-MediumOblique"
    public static let AvenirBlackOblique = "Avenir-BlackOblique"
    public static let AvenirHeavy = "Avenir-Heavy"
    public static let AvenirLightOblique = "Avenir-LightOblique"
    public static let AvenirOblique = "Avenir-Oblique"
    public static let AcademyEngravedLetPlain = "AcademyEngravedLetPlain"
    public static let DiwanMishafi = "DiwanMishafi"
    public static let FuturaCondensedMedium = "Futura-CondensedMedium"
    public static let FuturaCondensedExtraBold = "Futura-CondensedExtraBold"
    public static let FuturaMedium = "Futura-Medium"
    public static let FuturaMediumItalic = "Futura-MediumItalic"
    public static let Farah = "Farah"
    public static let KannadaSangamMN = "KannadaSangamMN"
    public static let KannadaSangamMNBold = "KannadaSangamMN-Bold"
    public static let ArialHebrewBold = "ArialHebrew-Bold"
    public static let ArialHebrewLight = "ArialHebrew-Light"
    public static let ArialHebrew = "ArialHebrew"
    public static let ArialMT = "ArialMT"
    public static let ArialBoldItalicMT = "Arial-BoldItalicMT"
    public static let ArialBoldMT = "Arial-BoldMT"
    public static let ArialItalicMT = "Arial-ItalicMT"
    public static let PartyLetPlain = "PartyLetPlain"
    public static let Chalkduster = "Chalkduster"
    public static let HiraKakuProNW6 = "HiraKakuProN-W6"
    public static let HiraKakuProNW3 = "HiraKakuProN-W3"
    public static let HoeflerTextItalic = "HoeflerText-Italic"
    public static let HoeflerTextRegular = "HoeflerText-Regular"
    public static let HoeflerTextBlack = "HoeflerText-Black"
    public static let HoeflerTextBlackItalic = "HoeflerText-BlackItalic"
    public static let OptimaRegular = "Optima-Regular"
    public static let OptimaExtraBlack = "Optima-ExtraBlack"
    public static let OptimaBoldItalic = "Optima-BoldItalic"
    public static let OptimaItalic = "Optima-Italic"
    public static let OptimaBold = "Optima-Bold"
    public static let PalatinoBold = "Palatino-Bold"
    public static let PalatinoRoman = "Palatino-Roman"
    public static let PalatinoBoldItalic = "Palatino-BoldItalic"
    public static let PalatinoItalic = "Palatino-Italic"
    public static let MalayalamSangamMNBold = "MalayalamSangamMN-Bold"
    public static let MalayalamSangamMN = "MalayalamSangamMN"
    public static let LaoSangamMN = "LaoSangamMN"
    public static let AlNileBold = "AlNile-Bold"
    public static let AlNile = "AlNile"
    public static let BradleyHandITCTTBold = "BradleyHandITCTT-Bold"
    public static let HiraMinProNW6 = "HiraMinProN-W6"
    public static let HiraMinProNW3 = "HiraMinProN-W3"
    public static let TrebuchetBoldItalic = "Trebuchet-BoldItalic"
    public static let TrebuchetMS = "TrebuchetMS"
    public static let TrebuchetMSBold = "TrebuchetMS-Bold"
    public static let TrebuchetMSItalic = "TrebuchetMS-Italic"
    public static let HelveticaBold = "Helvetica-Bold"
    public static let Helvetica = "Helvetica"
    public static let HelveticaLightOblique = "Helvetica-LightOblique"
    public static let HelveticaOblique = "Helvetica-Oblique"
    public static let HelveticaBoldOblique = "Helvetica-BoldOblique"
    public static let HelveticaLight = "Helvetica-Light"
    public static let CourierBoldOblique = "Courier-BoldOblique"
    public static let Courier = "Courier"
    public static let CourierBold = "Courier-Bold"
    public static let CourierOblique = "Courier-Oblique"
    public static let CochinBold = "Cochin-Bold"
    public static let Cochin = "Cochin"
    public static let CochinItalic = "Cochin-Italic"
    public static let CochinBoldItalic = "Cochin-BoldItalic"
    public static let DevanagariSangamMN = "DevanagariSangamMN"
    public static let DevanagariSangamMNBold = "DevanagariSangamMN-Bold"
    public static let OriyaSangamMN = "OriyaSangamMN"
    public static let OriyaSangamMNBold = "OriyaSangamMN-Bold"
    public static let SnellRoundhandBold = "SnellRoundhand-Bold"
    public static let SnellRoundhand = "SnellRoundhand"
    public static let SnellRoundhandBlack = "SnellRoundhand-Black"
    public static let ZapfDingbatsITC = "ZapfDingbatsITC"
    public static let BodoniSvtyTwoITCTTBold = "BodoniSvtyTwoITCTT-Bold"
    public static let BodoniSvtyTwoITCTTBook = "BodoniSvtyTwoITCTT-Book"
    public static let BodoniSvtyTwoITCTTBookIta = "BodoniSvtyTwoITCTT-BookIta"
    public static let VerdanaItalic = "Verdana-Italic"
    public static let VerdanaBoldItalic = "Verdana-BoldItalic"
    public static let Verdana = "Verdana"
    public static let VerdanaBold = "Verdana-Bold"
    public static let AmericanTypewriterCondensedLight = "AmericanTypewriter-CondensedLight"
    public static let AmericanTypewriter = "AmericanTypewriter"
    public static let AmericanTypewriterCondensedBold = "AmericanTypewriter-CondensedBold"
    public static let AmericanTypewriterLight = "AmericanTypewriter-Light"
    public static let AmericanTypewriterBold = "AmericanTypewriter-Bold"
    public static let AmericanTypewriterCondensed = "AmericanTypewriter-Condensed"
    public static let AvenirNextUltraLight = "AvenirNext-UltraLight"
    public static let AvenirNextUltraLightItalic = "AvenirNext-UltraLightItalic"
    public static let AvenirNextBold = "AvenirNext-Bold"
    public static let AvenirNextBoldItalic = "AvenirNext-BoldItalic"
    public static let AvenirNextDemiBold = "AvenirNext-DemiBold"
    public static let AvenirNextDemiBoldItalic = "AvenirNext-DemiBoldItalic"
    public static let AvenirNextMedium = "AvenirNext-Medium"
    public static let AvenirNextHeavyItalic = "AvenirNext-HeavyItalic"
    public static let AvenirNextHeavy = "AvenirNext-Heavy"
    public static let AvenirNextItalic = "AvenirNext-Italic"
    public static let AvenirNextRegular = "AvenirNext-Regular"
    public static let AvenirNextMediumItalic = "AvenirNext-MediumItalic"
    public static let BaskervilleItalic = "Baskerville-Italic"
    public static let BaskervilleSemiBold = "Baskerville-SemiBold"
    public static let BaskervilleBoldItalic = "Baskerville-BoldItalic"
    public static let BaskervilleSemiBoldItalic = "Baskerville-SemiBoldItalic"
    public static let BaskervilleBold = "Baskerville-Bold"
    public static let Baskerville = "Baskerville"
    public static let KhmerSangamMN = "KhmerSangamMN"
    public static let DidotItalic = "Didot-Italic"
    public static let DidotBold = "Didot-Bold"
    public static let Didot = "Didot"
    public static let SavoyeLetPlain = "SavoyeLetPlain"
    public static let BodoniOrnamentsITCTT = "BodoniOrnamentsITCTT"
    public static let Symbol = "Symbol"
    public static let MenloItalic = "Menlo-Italic"
    public static let MenloBold = "Menlo-Bold"
    public static let MenloRegular = "Menlo-Regular"
    public static let MenloBoldItalic = "Menlo-BoldItalic"
    public static let BodoniSvtyTwoSCITCTTBook = "BodoniSvtyTwoSCITCTT-Book"
    public static let DINAlternateBold = "DINAlternate-Bold"
    public static let Papyrus = "Papyrus"
    public static let PapyrusCondensed = "Papyrus-Condensed"
    public static let EuphemiaUCASItalic = "EuphemiaUCAS-Italic"
    public static let EuphemiaUCAS = "EuphemiaUCAS"
    public static let EuphemiaUCASBold = "EuphemiaUCAS-Bold"
    public static let TeluguSangamMN = "TeluguSangamMN"
    public static let TeluguSangamMNBold = "TeluguSangamMN-Bold"
    public static let BanglaSangamMNBold = "BanglaSangamMN-Bold"
    public static let BanglaSangamMN = "BanglaSangamMN"
    public static let Zapfino = "Zapfino"
    public static let BodoniSvtyTwoOSITCTTBook = "BodoniSvtyTwoOSITCTT-Book"
    public static let BodoniSvtyTwoOSITCTTBold = "BodoniSvtyTwoOSITCTT-Bold"
    public static let BodoniSvtyTwoOSITCTTBookIt = "BodoniSvtyTwoOSITCTT-BookIt"
    public static let DINCondensedBold = "DINCondensed-Bold"
    
}
